//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Backend.Shared.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin registered.
        /// </summary>
        internal static string AuthenticateController_AdminRegistered {
            get {
                return ResourceManager.GetString("AuthenticateController_AdminRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string AuthenticateController_AdminRole {
            get {
                return ResourceManager.GetString("AuthenticateController_AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string AuthenticateController_Error {
            get {
                return ResourceManager.GetString("AuthenticateController_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        internal static string AuthenticateController_InvalidCredentials {
            get {
                return ResourceManager.GetString("AuthenticateController_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Token.
        /// </summary>
        internal static string AuthenticateController_InvalidToken {
            get {
                return ResourceManager.GetString("AuthenticateController_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout from all devices.
        /// </summary>
        internal static string AuthenticateController_LogoutAll {
            get {
                return ResourceManager.GetString("AuthenticateController_LogoutAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string AuthenticateController_PasswordRequired {
            get {
                return ResourceManager.GetString("AuthenticateController_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string AuthenticateController_Success {
            get {
                return ResourceManager.GetString("AuthenticateController_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string AuthenticateController_Unauthorized {
            get {
                return ResourceManager.GetString("AuthenticateController_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        internal static string AuthenticateController_UserAlreadyExists {
            get {
                return ResourceManager.GetString("AuthenticateController_UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User creation failed.
        /// </summary>
        internal static string AuthenticateController_UserCreationFailed {
            get {
                return ResourceManager.GetString("AuthenticateController_UserCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        internal static string AuthenticateController_UserDoesNotExist {
            get {
                return ResourceManager.GetString("AuthenticateController_UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email is required.
        /// </summary>
        internal static string AuthenticateController_UserEmailRequired {
            get {
                return ResourceManager.GetString("AuthenticateController_UserEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is required.
        /// </summary>
        internal static string AuthenticateController_UserNameRequired {
            get {
                return ResourceManager.GetString("AuthenticateController_UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered.
        /// </summary>
        internal static string AuthenticateController_UserRegistered {
            get {
                return ResourceManager.GetString("AuthenticateController_UserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string AuthenticateController_UserRole {
            get {
                return ResourceManager.GetString("AuthenticateController_UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Science Club input.
        /// </summary>
        internal static string ScienceClubController_InvalidInput {
            get {
                return ResourceManager.GetString("ScienceClubController_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User input.
        /// </summary>
        internal static string UserController_InvalidInput {
            get {
                return ResourceManager.GetString("UserController_InvalidInput", resourceCulture);
            }
        }
    }
}
