name: Auto-Assign PR Reviewer

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Assign default reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ASSIGNEE: Pixel12pixel
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees \
            -d '{"assignees": ["'"$ASSIGNEE"'"]}'
          fi