name: most-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  POSTGRE_URL: ${{ secrets.POSTGRE_URL }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build